import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#1c5ec8',
    primaryColorHover: '#245fbf',
    primaryColorPressed: '#154da7',
    primaryColorSuppl: '#154da7',
    successColor: '#2e8b59',
    warningColor: '#c98517',
    errorColor: '#c53947',
    infoColor: '#2f7ed6',
    borderRadius: '10px',
    borderRadiusSmall: '8px',
    fontFamily:
      "'PingFang SC', 'Hiragino Sans GB', 'Noto Sans CJK SC', 'Microsoft YaHei', 'Segoe UI', sans-serif",
    textColorBase: '#13243c',
    textColor1: '#13243c',
    textColor2: '#3e556f',
    textColor3: '#6e839c',
    bodyColor: '#ffffff',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    dividerColor: '#d6e1f0',
    borderColor: '#d6e1f0',
    tableColor: '#ffffff',
    tableColorHover: '#f7faff',
    tableHeaderColor: '#f2f6fd',
    scrollbarColor: 'rgba(19, 36, 60, 0.2)',
    scrollbarColorHover: 'rgba(19, 36, 60, 0.32)',
  },
  Button: {
    textColorPrimary: '#ffffff',
    textColorHoverPrimary: '#ffffff',
    textColorPressedPrimary: '#ffffff',
    colorHoverPrimary: '#245fbf',
    colorPressedPrimary: '#154da7',
    colorFocusPrimary: '#245fbf',
    borderPrimary: '1px solid #1c5ec8',
    borderHoverPrimary: '1px solid #245fbf',
    borderPressedPrimary: '1px solid #154da7',
    borderFocusPrimary: '1px solid #245fbf',
    borderRadiusTiny: '8px',
    borderRadiusSmall: '10px',
    borderRadiusMedium: '10px',
    borderRadiusLarge: '12px',
  },
  Input: {
    borderHover: '1px solid #9bb3d4',
    borderFocus: '1px solid #1c5ec8',
    boxShadowFocus: '0 0 0 2px rgba(28, 94, 200, 0.14)',
    colorFocus: '#ffffff',
    color: '#ffffff',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderHover: '1px solid #9bb3d4',
        borderFocus: '1px solid #1c5ec8',
        boxShadowFocus: '0 0 0 2px rgba(28, 94, 200, 0.14)',
      },
    },
  },
  Card: {
    borderRadius: '14px',
    borderColor: '#d6e1f0',
    titleTextColor: '#13243c',
    color: '#ffffff',
    actionColor: '#f6f9fe',
  },
  Tabs: {
    tabTextColorActiveLine: '#154da7',
    tabTextColorLine: '#3e556f',
    tabTextColorHoverLine: '#245fbf',
    barColor: '#1c5ec8',
  },
  DataTable: {
    borderColor: '#d6e1f0',
    thColor: '#f2f6fd',
    tdColor: '#ffffff',
    tdColorHover: '#f7faff',
    thTextColor: '#3e556f',
    tdTextColor: '#13243c',
    borderRadius: '12px',
  },
  Tag: {
    borderRadius: '999px',
  },
}
